### ISSUE TITLE
Screenshot in your readme?  Also.... default branch makes the repo appear empty...

### ISSUE THREAD

**Issue by PySimpleGUI** [pyrataria/B64-Conv#1]
Hi!

I apologize for posting in English, but, unlike you, I'm not bi-lingual at a level that's enough for a message like this.

------------

## Default Branch 
The biggest issue I saw was when I visit your repo, I see this:

![image](https://user-images.githubusercontent.com/46163555/146556866-cd72ab45-ff8f-49db-b79a-2723f36988e4.png)

It wasn't until I changed the repo to **master** that I saw the files

![image](https://user-images.githubusercontent.com/46163555/146556978-8b375f74-a04c-48e2-8f6b-830a96539369.png)

----------------

## Readme Screenshot

I would ❤ to see what your GUIs look like!  And I'm SURE other visitors would too.

There is a YouTube video I made showing how you can use GitHub Issue to add screenshots to your readme.

I don't know if you've seen the PySimpleGUI utility `psgresizer` that was released not too long ago that does a base64 conversion and leaves the results on the clipboard.  If not, take a look.  You can pip install it.... `pip install psgresizer`.

-------------------------------------

## Keep Building!!  💪

You're on the right path!   You're learning to program the way I believe is the best.... by making things... by solving problems.... by having an idea and then figuring out for yourself how to get from idea to result on the screen.  Please keep on making and sharing your work!  You're motivating others in the process.

**Comment by pyrataria** [comment]
Thank you for support <3 and thanks for the tips ;D

**Comment by PySimpleGUI** [comment]
The same for you!  Thank you for the support and thank you for the tips.  I learned a cool trick today from you.
